name: Rust CI
on: push
jobs:
  clippy:
    name: clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust nightly
        run: |
          rustup toolchain update --no-self-update nightly
          rustup default nightly
          rustup component add clippy
      - name: Run clippy
        run: cargo clippy -- -D warnings
  rustfmt:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust nightly
        run: |
          rustup toolchain update --no-self-update nightly
          rustup default nightly
          rustup component add rustfmt
      - name: Run rustfmt
        run: cargo fmt -- --check
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust nightly
        run: |
          rustup toolchain update --no-self-update nightly
          rustup default nightly
      - name: Run build
        run: cargo build
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust nightly
        run: |
          rustup toolchain update --no-self-update nightly
          rustup default nightly
      - name: Run tests
        run: cargo test
