name: Database CI
on: push
jobs:
  migrate:
    name: build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: password123
          POSTGRES_USER: rootgame
          POSTGRES_DB: rootgame
          DB_PORT: 5432
        ports:
          - 5432:5432
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install Rust nightly
        run: |
          rustup toolchain update --no-self-update nightly
          rustup default nightly
          rustup component add clippy
          cargo install sqlx-cli
      - name: Setup database
        run: |
          sqlx database create
          sqlx migrate run
        env:
          DATABASE_URL: postgres://rootgame:password123@localhost:5432/rootgame
      - name: Check sqlx-data.json
        run: cargo sqlx prepare --check
